# https://github.com/blacktop/docker-kafka-alpine/blob/master/docker-compose.yml
version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: blacktop/kafka:${VERSION:-latest}
    command: zookeeper-server-start.sh config/zookeeper.properties
    ports:
      - 2181:2181
    # network_mode: bridge
  kafka:
    image: blacktop/kafka:${VERSION:-latest}
    depends_on:
      - zookeeper
    entrypoint: /wait-for-it.sh zookeeper:2181 -s --timeout=5 -- /kafka-entrypoint.sh
    command: kafka-server-start.sh config/server.properties
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_CREATE_TOPICS=docker:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_HEAP_OPTS=-Xmx2G -Xms2G
    ports:
      - 9092
    links:
     - zookeeper
    volumes:
      # - kafka-logs:/tmp/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    # network_mode: bridge

volumes:
  kafka-logs:
